package com.geomap.utils

object CONSTANTS {
    const val FLAG_ZERO = "0"
    const val FLAG_ONE = "1"
    const val FLAG_TWO = "2"
    const val FLAG_THREE = "3"
    const val FLAG_FOUR = "4"
    const val FLAG_FIVE = "5"
    const val FLAG_SIX = "6"
    const val FLAG_SEVEN = "7"
    const val FLAG_EIGHT = "8"
    const val FLAG_NINE = "9"
    const val FLAG_TEN = "10"
    const val FLAG_ELEVEN = "11"
    const val FLAG_TWELVE = "12"
    const val FLAG_THIRTEEN = "13"
    const val FLAG_FORTEEN = "14"
    const val FLAG_FIFTEEN = "15"
    const val YEAR_TO_DATE_FORMAT = "yyyy-MM-dd"
    const val TWENTY_FOUR_HOUR_FORMAT_WITH_SECOND = "HH:mm:ss"
    const val TWELVE_HOUR_FORMAT_WITH_AM_PM = "hh:mm a"
    const val MONTH_DATE_YEAR_FORMAT = "MMM dd, yyyy"
    const val DATE_MONTH_YEAR_FORMAT = "dd MMM, yyyy"
    const val DATE_MONTH_YEAR_FORMAT_z = "dd MMM, yyyy hh:mm a"
    const val DATE_MONTH_YEAR_FORMAT_z_D = "dd MMM, yyyy\nhh:mm a"
    const val DATE_MONTH_YEAR_FORMAT1 = "dd MM yyyy"
    const val DATE_MONTH_YEAR_FORMAT_TIME = "dd MMMM, yyyy hh:mm:ss aa"
    const val DATE_MONTH_YEAR_FORMAT_TIME_with_Timzone = "yyyy-MM-dd HH:mm:ssZZ"
    const val SERVER_TIME_FORMAT = "yyyy-MM-dd HH:mm:ss"
    const val TWENTY_FOUR_HH_MM_FORMAT = "HH:mm"
    const val FCMToken = "FCMToken"
    const val Token = "Token"
    const val MULTIPART_FORMAT = "multipart/form-data"

    const val PREFE_ACCESS_USERDATA = "UserData"
    const val PREFE_ACCESS_ArrayData = "ArrayData"
    const val PREFE_ACCESS_SplashData = "PREFE_ACCESS_SplashData"
    const val attributeData = "attributeData"
    const val rockStrength = "rockStrength"
    const val sampleCollected = "sampleCollected"
    const val typeOfFaults = "typeOfFaults"
    const val typeOfGeologicalStructures = "typeOfGeologicalStructures"
    const val waterCondition = "waterCondition"
    const val weatheringData = "weatheringData"

    const val userId = "userId"
    const val deviceToken = "deviceToken"
    const val deviceId = "deviceId"
    const val deviceType = "deviceType"
    const val name = "Name"
    const val email = "Email"
    const val mobile = "Mobile"
    const val dob = "DOB"
    const val profileImage = "profileImage"
    const val createdAt = "createdAt"
    const val updatedAt = "updatedAt"
    const val attributeId = "attributeId"
    const val checkLogin = "checkLogin"


    const val supportTitle = "supportTitle"
    const val supportText = "supportText"
    const val supportEmail = "supportEmail"
    const val isForce = "isForce"
    const val state = "State"
    const val report = "report"
    const val id = "id"

    @JvmField var Web = "Web"
    const val PREF_KEY_Splash = "Splash"
    const val PREF_KEY_SplashKey = "SplashKey"
}
